apiVersion: v1
kind: Pod
metadata:
    name: resource-pod
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command: ['sh','-c','while true;do sleep 3600;done']
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          cpu: "500m"
          memory: "128Mi"