apiVersion: v1
kind: Pod
metadata:
  name: stress-test-pod
spec:
  containers:
  - name: stress-test-container
    image: busybox
    command: ['sh','-c','while true;do sleep 3600;done']
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
