apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-flask-deploy
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-flask
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-flask
        env: front-end
        version: v1
    spec:
      containers:
        - name: web-flask-cont
          image: mefekadocker/web-flask:0.2 
          ports:
            - containerPort: 80
    