apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: nginx
spec:
  volumes:
    - name: web-pv
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
  - name: web-nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: web-pv
